apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    run: git-backup-local
  name: git-backup-local
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: backupgit-cron
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - kubectl exec -it `kubectl get pods -l deploymentconfig=gitlab-ce | egrep
              -o "gitlab-ce[a-zA-Z0-9-]+"` gitlab-rake gitlab:backup:create
            image: roffe/kubectl@sha256:a7b9bbd4263a19b7bb9dc6aec308eae96f7426f08584377874f4404e73606842
            imagePullPolicy: IfNotPresent
            name: pi
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: 4kubectl
          serviceAccountName: 4kubectl
          terminationGracePeriodSeconds: 30
  schedule: 00 21 * * ?
  successfulJobsHistoryLimit: 1
  suspend: false
status: {}
